name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@5037c6f1012cc5ea0b9f03fedbaf9955ed9e51e0 # master
      - name: Style check
        run: brew style pantheon-systems/external/terminus
      - name: Audit formula
        run: brew audit --strict pantheon-systems/external/terminus
