name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@841d750a0ed9262d3c3ca31f2173974696bc261a # master
      - name: Style check
        run: brew style pantheon-systems/external/terminus
      - name: Audit formula
        run: brew audit --strict pantheon-systems/external/terminus
